name: shopify
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.0.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.3
  http: ^1.1.0
  shimmer: ^3.0.0
  glass: ^2.0.0+1
  flutter_svg: ^2.0.9
  lottie: ^3.1.2
  get_storage: ^2.1.1
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.16.5
  webview_flutter_wkwebview: ^3.9.4
  device_preview: ^1.2.0
  otp_text_field: ^1.1.3
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  country_picker: ^2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  mongo_dart: ^0.10.3

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/